/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NasabahController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Nasabah;

/**
 *
 * @author NEW ASUS
 */
public class FormNasabah extends javax.swing.JFrame {

    /**
     * Creates new form FormNasabah
     */
    public FormNasabah() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
    }
    
     private void tampilData() {

        NasabahController controller = new NasabahController();

        DefaultTableModel model =
                (DefaultTableModel) TableNasabah.getModel();

        model.setRowCount(0);

        for (Nasabah data : controller.getAllNasabah()) {

            model.addRow(new Object[]{
                data.getIdNasabah(),
                data.getNama(),
                data.getAlamat(),
                data.getNoHp()
            });

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInputNasabah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldIdNasabah = new javax.swing.JTextField();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldAlamat = new javax.swing.JTextField();
        TextFieldNoHp = new javax.swing.JTextField();
        ButtonSimpan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        PanelDataNasabah = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNasabah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInputNasabah.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM DATA NASABAH");

        jLabel2.setText("ID Nasabah                       :");

        jLabel3.setText("Nama                                :");

        jLabel4.setText("Alamat                               :");

        jLabel5.setText("No. HP                                :");

        TextFieldIdNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdNasabahActionPerformed(evt);
            }
        });

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInputNasabahLayout = new javax.swing.GroupLayout(PanelInputNasabah);
        PanelInputNasabah.setLayout(PanelInputNasabahLayout);
        PanelInputNasabahLayout.setHorizontalGroup(
            PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonKembali)
                            .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                                    .addComponent(ButtonSimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonEdit)
                                    .addGap(18, 18, 18)
                                    .addComponent(ButtonHapus)
                                    .addGap(18, 18, 18)
                                    .addComponent(ButtonReset))
                                .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                                    .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextFieldNama)
                                            .addComponent(TextFieldAlamat)
                                            .addComponent(TextFieldNoHp, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                        .addComponent(TextFieldIdNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelInputNasabahLayout.setVerticalGroup(
            PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputNasabahLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(ButtonKembali)
                .addGap(18, 18, 18)
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldIdNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(PanelInputNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonReset))
                .addGap(16, 16, 16))
        );

        PanelDataNasabah.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout PanelDataNasabahLayout = new javax.swing.GroupLayout(PanelDataNasabah);
        PanelDataNasabah.setLayout(PanelDataNasabahLayout);
        PanelDataNasabahLayout.setHorizontalGroup(
            PanelDataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        PanelDataNasabahLayout.setVerticalGroup(
            PanelDataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(153, 204, 255));

        TableNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "No HP"
            }
        ));
        TableNasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNasabahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNasabah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelInputNasabah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PanelDataNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInputNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDataNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        if(TextFieldIdNasabah.getText().trim().isEmpty() ||
        TextFieldNama.getText().trim().isEmpty() ||
        TextFieldAlamat.getText().trim().isEmpty() ||
        TextFieldNoHp.getText().trim().isEmpty()){

         JOptionPane.showMessageDialog(this,
                 "Semua data wajib diisi!");

         return;
     }
        Nasabah n = new Nasabah();

        n.setIdNasabah(Integer.parseInt(TextFieldIdNasabah.getText()));
        n.setNama(TextFieldNama.getText());
        n.setAlamat(TextFieldAlamat.getText());
        n.setNoHp(TextFieldNoHp.getText());

        NasabahController controller = new NasabahController();

        if(controller.simpan(n)){

            JOptionPane.showMessageDialog(this,
                    "Data berhasil disimpan");

            tampilData();

            ButtonResetActionPerformed(null);

    }//GEN-LAST:event_ButtonSimpanActionPerformed
    }
    private void TextFieldIdNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdNasabahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdNasabahActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
       Nasabah n = new Nasabah();

        n.setIdNasabah(Integer.parseInt(TextFieldIdNasabah.getText()));
        n.setNama(TextFieldNama.getText());
        n.setAlamat(TextFieldAlamat.getText());
        n.setNoHp(TextFieldNoHp.getText());

        NasabahController controller = new NasabahController();
        if(controller.edit(n)){

            JOptionPane.showMessageDialog(this,
                    "Data berhasil diupdate");

            tampilData();
            ButtonResetActionPerformed(null);
    }//GEN-LAST:event_ButtonEditActionPerformed
    }
    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        TextFieldIdNasabah.setText("");
        TextFieldNama.setText("");
        TextFieldAlamat.setText("");
        TextFieldNoHp.setText("");
        
        TextFieldNama.requestFocus();
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus data?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

            if(pilih==JOptionPane.YES_OPTION){
                NasabahController controller = new NasabahController();
                if(controller.delete(TextFieldIdNasabah.getText())){
                    JOptionPane.showMessageDialog(this,
                            "Data berhasil dihapus");

        tampilData();

        ButtonResetActionPerformed(null);
                }
            }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void TableNasabahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNasabahMouseClicked
        // TODO add your handling code here:
        int row = TableNasabah.getSelectedRow();

        TextFieldIdNasabah.setText(TableNasabah.getValueAt(row, 0).toString());
        TextFieldNama.setText(TableNasabah.getValueAt(row, 1).toString());
        TextFieldAlamat.setText(TableNasabah.getValueAt(row, 2).toString());
        TextFieldNoHp.setText(TableNasabah.getValueAt(row, 3).toString());
    }//GEN-LAST:event_TableNasabahMouseClicked

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNasabah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JPanel PanelDataNasabah;
    private javax.swing.JPanel PanelInputNasabah;
    private javax.swing.JTable TableNasabah;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldIdNasabah;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNoHp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
