/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SampahController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sampah;

/**
 *
 * @author NEW ASUS
 */
public class FormSampah extends javax.swing.JFrame {

    /**
     * Creates new form FormSampah
     */
    public FormSampah() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInputSampah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldIdSampah = new javax.swing.JTextField();
        TextFieldNamaSampah = new javax.swing.JTextField();
        TextFieldHarga = new javax.swing.JTextField();
        ButtonSimpan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        PanelDataSampah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSampah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInputSampah.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM SAMPAH");

        jLabel2.setText("ID Sampah               :");

        jLabel3.setText("Nama Sampah             :");

        jLabel4.setText("Harga / Kg              :");

        TextFieldIdSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdSampahActionPerformed(evt);
            }
        });

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEditMouseClicked(evt);
            }
        });
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonResetMouseClicked(evt);
            }
        });
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInputSampahLayout = new javax.swing.GroupLayout(PanelInputSampah);
        PanelInputSampah.setLayout(PanelInputSampahLayout);
        PanelInputSampahLayout.setHorizontalGroup(
            PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputSampahLayout.createSequentialGroup()
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInputSampahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(ButtonReset))
                    .addGroup(PanelInputSampahLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonKembali)
                            .addGroup(PanelInputSampahLayout.createSequentialGroup()
                                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldIdSampah)
                                    .addComponent(TextFieldNamaSampah)
                                    .addComponent(TextFieldHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(PanelInputSampahLayout.createSequentialGroup()
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInputSampahLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInputSampahLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInputSampahLayout.setVerticalGroup(
            PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputSampahLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addGap(18, 18, 18)
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldIdSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldNamaSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(PanelInputSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonReset))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        PanelDataSampah.setBackground(new java.awt.Color(102, 153, 255));

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));

        TableSampah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Sampah", "Harga/Kg"
            }
        ));
        TableSampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSampahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSampah);

        javax.swing.GroupLayout PanelDataSampahLayout = new javax.swing.GroupLayout(PanelDataSampah);
        PanelDataSampah.setLayout(PanelDataSampahLayout);
        PanelDataSampahLayout.setHorizontalGroup(
            PanelDataSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataSampahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDataSampahLayout.setVerticalGroup(
            PanelDataSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDataSampahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInputSampah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDataSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInputSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDataSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData(){

    DefaultTableModel model = (DefaultTableModel) TableSampah.getModel();
    model.setRowCount(0);
    SampahController controller = new SampahController();
    List<Sampah> list = controller.getAllSampah();

    for(Sampah s : list){
        Object[] row = {
            s.getIdSampah(),
            s.getNamaSampah(),
            s.getHarga()
        };
        model.addRow(row);
    }
}
    
    private void TextFieldIdSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdSampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdSampahActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        Sampah s = new Sampah();

        s.setIdSampah(Integer.parseInt(TextFieldIdSampah.getText()));
        s.setNamaSampah(TextFieldNamaSampah.getText());
        s.setHarga(Double.parseDouble(TextFieldHarga.getText()));

        SampahController controller = new SampahController();

        if(controller.edit(s)){

            JOptionPane.showMessageDialog(this,"Data berhasil diubah");

            tampilData();

        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        if(TextFieldIdSampah.getText().trim().isEmpty() ||
        TextFieldIdSampah.getText().trim().isEmpty() ||
        TextFieldNamaSampah.getText().trim().isEmpty() ||
        TextFieldHarga.getText().trim().isEmpty()){

         JOptionPane.showMessageDialog(this,
                 "Semua data wajib diisi!");

         return;
        }
        Sampah s = new Sampah();

        s.setIdSampah(Integer.parseInt(TextFieldIdSampah.getText()));
        s.setNamaSampah(TextFieldNamaSampah.getText());
        s.setHarga(Double.parseDouble(TextFieldHarga.getText()));

        SampahController controller = new SampahController();
        if(controller.simpan(s)){
            JOptionPane.showMessageDialog(this,"Data berhasil disimpan");
            tampilData();
        }else{
            JOptionPane.showMessageDialog(this,"Data gagal disimpan");
        }
        TextFieldIdSampah.setText("");
        TextFieldNamaSampah.setText("");
        TextFieldHarga.setText("");
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        String id = TextFieldIdSampah.getText();

        SampahController controller = new SampahController();
        if(controller.delete(id)){
            JOptionPane.showMessageDialog(this,"Data berhasil dihapus");
            tampilData();
        }
        TextFieldIdSampah.setText("");
        TextFieldNamaSampah.setText("");
        TextFieldHarga.setText("");
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        TextFieldIdSampah.setText("");
        TextFieldNamaSampah.setText("");
        TextFieldHarga.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonResetMouseClicked

    private void ButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditMouseClicked

    private void TableSampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSampahMouseClicked
        // TODO add your handling code here:
        int row = TableSampah.getSelectedRow();

        TextFieldIdSampah.setText(TableSampah.getValueAt(row,0).toString());
        TextFieldNamaSampah.setText(TableSampah.getValueAt(row,1).toString());
        TextFieldHarga.setText(TableSampah.getValueAt(row,2).toString());
    }//GEN-LAST:event_TableSampahMouseClicked

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSampah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JPanel PanelDataSampah;
    private javax.swing.JPanel PanelInputSampah;
    private javax.swing.JTable TableSampah;
    private javax.swing.JTextField TextFieldHarga;
    private javax.swing.JTextField TextFieldIdSampah;
    private javax.swing.JTextField TextFieldNamaSampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
