/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TransaksiController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Transaksi;
import dao.NasabahDAO;
import dao.SampahDAO;
import java.util.List;
import model.Nasabah;
import model.Sampah;

/**
 *
 * @author NEW ASUS
 */
public class FormTransaksi extends javax.swing.JFrame {
        private TransaksiController controller = new TransaksiController();
        private DefaultTableModel model;
        
        private NasabahDAO nasabahDAO = new NasabahDAO();
        private SampahDAO sampahDAO = new SampahDAO();

        private List<Nasabah> listNasabah;
        private List<Sampah> listSampah;
    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        TextFieldIdTransaksi.setEnabled(false);
        TextFieldTanggal.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
        TextFieldHarga.setEditable(false);
        model = (DefaultTableModel) TableTransaksi.getModel();
        setLocationRelativeTo(null);
        loadNasabah();
        loadSampah();
        tampilData();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTransaksi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ButtonSimpan = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        TextFieldIdTransaksi = new javax.swing.JTextField();
        TextFieldTanggal = new javax.swing.JTextField();
        ComboBoxNasabah = new javax.swing.JComboBox();
        ComboBoxSampah = new javax.swing.JComboBox();
        TextFieldBerat = new javax.swing.JTextField();
        TextFieldHarga = new javax.swing.JTextField();
        TextFieldTotal = new javax.swing.JTextField();
        ButtonKembali = new javax.swing.JButton();
        PanelData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTransaksi.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM TRANSAKSI");

        jLabel2.setText("ID Transaksi");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Nasabah");

        jLabel5.setText("Sampah");

        jLabel6.setText("Berat (Kg)");

        jLabel7.setText("Harga / Kg");

        jLabel8.setText("Total");

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSimpanMouseClicked(evt);
            }
        });
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        TextFieldIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdTransaksiActionPerformed(evt);
            }
        });

        TextFieldTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTanggalActionPerformed(evt);
            }
        });

        ComboBoxNasabah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNasabahActionPerformed(evt);
            }
        });

        ComboBoxSampah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSampahActionPerformed(evt);
            }
        });

        TextFieldBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBeratActionPerformed(evt);
            }
        });
        TextFieldBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldBeratKeyReleased(evt);
            }
        });

        TextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldHargaActionPerformed(evt);
            }
        });

        TextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTotalActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTransaksiLayout = new javax.swing.GroupLayout(PanelTransaksi);
        PanelTransaksi.setLayout(PanelTransaksiLayout);
        PanelTransaksiLayout.setHorizontalGroup(
            PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransaksiLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5))
                    .addGroup(PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14))
                    .addGroup(PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5))
                    .addGroup(PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(ButtonKembali)
                        .addGap(5, 5, 5))
                    .addGroup(PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextFieldHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldIdTransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldTanggal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxNasabah, javax.swing.GroupLayout.Alignment.LEADING, 0, 298, Short.MAX_VALUE)
                    .addComponent(ComboBoxSampah, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldBerat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldTotal))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransaksiLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(ButtonSimpan)
                        .addGap(63, 63, 63)
                        .addComponent(ButtonReset)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))))
        );
        PanelTransaksiLayout.setVerticalGroup(
            PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ButtonKembali)
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(PanelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonReset)))
        );

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));

        TableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tanggal", "Nasabah", "Sampah", "Berat", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableTransaksi);

        javax.swing.GroupLayout PanelDataLayout = new javax.swing.GroupLayout(PanelData);
        PanelData.setLayout(PanelDataLayout);
        PanelDataLayout.setHorizontalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PanelDataLayout.setVerticalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData() {
    model.setRowCount(0);

    ArrayList<Transaksi> list = controller.getAll();

    for (Transaksi t : list) {

        Object[] row = {
            t.getIdTransaksi(),
            t.getTanggal(),
            t.getNamaNasabah(),
            t.getNamaSampah(),
            t.getBerat(),
            t.getHarga(),
            t.getTotal()
        };
        model.addRow(row);
    }
}
    public void loadNasabah() {
        
    listNasabah = nasabahDAO.getAllNasabah();
    ComboBoxNasabah.removeAllItems();
    for (Nasabah n : listNasabah) {
        ComboBoxNasabah.addItem(n.getNama());
    }

}
    private void loadSampah() {

    listSampah = sampahDAO.getAllSampah();
    ComboBoxSampah.removeAllItems();
    for (Sampah s : listSampah) {
        ComboBoxSampah.addItem(s.getNamaSampah());
    }
}
    private void hitungTotal() {
      try{

        if(TextFieldHarga.getText().trim().equals(""))
            return;
        if(TextFieldBerat.getText().trim().equals(""))
            return;
        double harga=Double.parseDouble(TextFieldHarga.getText());
        double berat=Double.parseDouble(TextFieldBerat.getText());
        double total=harga*berat;

        TextFieldTotal.setText(String.valueOf(total));
    }catch(Exception e){
        TextFieldTotal.setText("");
    }
}
    private void reset() {

    TextFieldTanggal.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    TextFieldBerat.setText("");
    TextFieldHarga.setText("");
    TextFieldTotal.setText("");

    ComboBoxNasabah.setSelectedIndex(0);
    ComboBoxSampah.setSelectedIndex(0);

}
    
    private void ComboBoxNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNasabahActionPerformed
        // TODO add your handling code here:
        if (ComboBoxNasabah.getSelectedIndex() == -1) {
        return;
         }
    }//GEN-LAST:event_ComboBoxNasabahActionPerformed

    private void TextFieldIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdTransaksiActionPerformed

    private void TextFieldTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTanggalActionPerformed

    private void ComboBoxSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSampahActionPerformed
        // TODO add your handling code here:
        if(listSampah==null)
        return;
    int index=ComboBoxSampah.getSelectedIndex();
    if(index<0)
        return;
    Sampah s=listSampah.get(index);
    TextFieldHarga.setText(String.valueOf((int)s.getHarga()));
    hitungTotal();


    }//GEN-LAST:event_ComboBoxSampahActionPerformed

    private void TextFieldBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBeratActionPerformed

    private void TextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldHargaActionPerformed

    private void TextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTotalActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {

        Transaksi t = new Transaksi();
        if (TextFieldBerat.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Berat belum diisi");
        return;}
        
        TextFieldIdTransaksi.setEditable(false);
        
        t.setTanggal(java.sql.Date.valueOf(TextFieldTanggal.getText()));
        
        Nasabah n = listNasabah.get(ComboBoxNasabah.getSelectedIndex());
        t.setIdNasabah(n.getIdNasabah());
        
        Sampah s = listSampah.get(ComboBoxSampah.getSelectedIndex());
        t.setIdSampah(s.getIdSampah());
        
        t.setBerat(Double.parseDouble(TextFieldBerat.getText()));
       t.setTotal(Double.parseDouble(TextFieldTotal.getText()));

        controller.simpan(t);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        tampilData();
        reset();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSimpanMouseClicked

    private void TextFieldBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldBeratKeyReleased
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_TextFieldBeratKeyReleased

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
         new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JComboBox ComboBoxNasabah;
    private javax.swing.JComboBox ComboBoxSampah;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelTransaksi;
    private javax.swing.JTable TableTransaksi;
    private javax.swing.JTextField TextFieldBerat;
    private javax.swing.JTextField TextFieldHarga;
    private javax.swing.JTextField TextFieldIdTransaksi;
    private javax.swing.JTextField TextFieldTanggal;
    private javax.swing.JTextField TextFieldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
